apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ixct
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ixct
    app.kubernetes.io/part-of: tkrw-pr712-0075-0072-app
  name: devfile-sample-ixct
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ixct
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ixct
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-ixct@sha256:90c1a8f2014c763d8157deaaad4b35f1393024bc45093a17cca758da69d19d8f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
